Repository albertnahas/Lingwars, pull requests merged in 2022-06, with the labels that each got.

#34 add leaving confirmation message
  cypress/integration/Game.spec.tsx
  src/App.tsx
  src/components/Game/GameContainer.tsx
  src/components/Landing/Landing.tsx
  src/components/SideDrawer/SideDrawer.tsx
  src/hooks/useChallenge.tsx
  src/molecules/ConfirmDialog/ConfirmDialog.tsx
Labels: enhancement

#36 play with bot
  firebase.json
  functions/index.js
  src/components/MainMenu/MainMenu.tsx
  src/hooks/useChallengeSetup.tsx
  src/hooks/useCurrentUser.tsx
  src/molecules/ChallengeSetupDialog/ChallengeSetupDialog.tsx
  src/utils/helpers.ts
Labels: feature

#40 Fix single player
  src/components/Game/GameContainer.tsx
  src/components/MainMenu/MainMenu.tsx
  src/hooks/useChallenge.tsx
  src/store/challengeSlice.ts
  src/types/state.ts
Labels: bug

#37 Add game info
  src/components/ChallengeInfo/ChallengeInfo.tsx
  src/components/Game/Game.tsx
Labels: enhancement

#41 fix challenge types
  src/components/ChallengeInfo/ChallengeInfo.tsx
  src/components/Game/Game.tsx
Labels: bug

#43 Chore/control pages
  cypress/integration/App.spec.tsx
  src/components/ControlPages/Privacy/Privacy.tsx
  src/components/ControlPages/Terms/Terms.tsx
  src/components/Footer/Footer.tsx
Labels: documentation

#47 Feat/learning
  src/components/ChallengeInfo/ChallengeInfo.tsx
  src/components/ControlPages/Terms/Terms.tsx
  src/components/Learn/Learn.tsx
Labels: enhancement

#48 Emoji in Donate
  src/components/Game/GameContainer.tsx
  src/molecules/DonationDialog/DonationDialog.tsx
Labels: enhancement

#55 Bug/typography issue
  src/components/Round/Round.tsx
  src/molecules/FeedbackForm/FeedbackForm.tsx
Labels: bug

#58 Chore/account deletion
  src/components/ControlPages/Privacy/Privacy.tsx
  src/components/ControlPages/Terms/Terms.tsx
  src/components/Profile/DeleteAccountForm.tsx
Labels: documentation

#63 Bug/stop timer on answer
  src/components/Round/Round.tsx
Labels: bug

#62 Feat/thank you donation
  src/molecules/DonationDialog/DonationDialog.tsx
  src/molecules/FeedbackForm/FeedbackForm.tsx
Labels: enhancement

#64 Feat/about us
  cypress/integration/App.spec.tsx
  src/components/ControlPages/About/About.tsx
  src/components/Footer/Footer.tsx
  src/components/SideDrawer/SideDrawer.tsx
Labels: documentation

#67 Chore/sitemap
  public/robots.txt
  public/sitemap.xml
Labels: documentation, enhancement

#69 add 404 page
  src/components/ControlPages/PageNotFound/PageNotFound.tsx
  src/components/Nav/Nav.tsx
  src/components/Round/Round.tsx
  src/icons/PageNotFound/PageNotFoundImg.tsx
Labels: feature

#76 Chore/seo
  index.html
  src/atoms/ProgressRing/ProgressRing.tsx
  src/components/Footer/Footer.tsx
  src/components/Landing/Landing.tsx
  src/components/Profile/Profile.tsx
Labels: enhancement

#81 add progress bar when audio is loading
  src/molecules/Waveform/Waveform.tsx
Labels: bug, enhancement

#82 add submit lang form
  src/components/ControlPages/About/About.tsx
  src/components/Footer/Footer.tsx
  src/components/SideDrawer/SideDrawer.tsx
Labels: enhancement

#86 fix replaceAll
  src/components/Round/Round.tsx
Labels: bug

#89 fix timer bug
  src/components/Round/Round.tsx
  src/molecules/Waveform/Waveform.tsx
Labels: bug
